######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 26 11:52:29 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += webkit

